Supermart Grocery Sales - Retail Analytics Dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#reading csv file
df = pd.read_csv("Supermart Grocery Sales - Retail Analytics Dataset.csv")
df.sample(5)

,Order ID,Customer Name,Category,Sub Category,City,Order Date,Region,Sales,Discount,Profit,State
5697,OD5698,Alan,Fruits & Veggies,Fresh Vegetables,Karur,3/19/2015,South,824,0.28,230.72,Tamil Nadu
4791,OD4792,Ram,Food Grains,Dals & Pulses,Bodi,7/18/2018,West,2430,0.29,170.10,Tamil Nadu
354,OD355,Surya,Bakery,Biscuits,Kanyakumari,04-08-2017,East,743,0.35,289.77,Tamil Nadu
3804,OD3805,Ramesh,Bakery,Biscuits,Tenkasi,12/14/2015,East,1050,0.25,252.00,Tamil Nadu
3101,OD3102,Veronica,Fruits & Veggies,Organic Fruits,Bodi,12/29/2017,West,621,0.10,279.45,Tamil Nadu

In [3]:
#dropping useless column
df.drop(["Order ID"], axis= 1, inplace=True)

In [4]:
#viewing the row and column or shape
df.shape

(9994, 10)

In [5]:
#viewing the size of the dataframe
df.size

99940

In [6]:
#viewing the columns in dataframe
df.columns

Index(['Customer Name', 'Category', 'Sub Category', 'City', 'Order Date',
       'Region', 'Sales', 'Discount', 'Profit', 'State'],
      dtype='str')

In [7]:
#gathering the info of the df
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer Name  9994 non-null   str
 1   Category       9994 non-null   str
 2   Sub Category   9994 non-null   str
 3   City           9994 non-null   str
 4   Order Date     9994 non-null   str
 5   Region         9994 non-null   str
 6   Sales          9994 non-null   int64
 7   Discount       9994 non-null   float64
 8   Profit         9994 non-null   float64
 9   State          9994 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 780.9 KB

In [8]:
#Viewing the total null value in dataframe
df.isna().sum()

Customer Name    0
Category         0
Sub Category     0
City             0
Order Date       0
Region           0
Sales            0
Discount         0
Profit           0
State            0
dtype: int64

In [9]:
#seeing the unique values in the customer name column
df["Customer Name"].unique()

<StringArray>
[  'Harish',    'Sudha',  'Hussain',  'Jackson',  'Ridhesh',   'Adavan',
    'Jonas',    'Hafiz', 'Krithika',   'Ganesh',    'Yadav',   'Sharon',
     'Peer',   'Sundar',   'Ramesh',     'Alan',   'Arutra',  'Haseena',
    'Verma',   'Muneer', 'Veronica',     'Shah',   'Mathew',    'Akash',
      'Anu',  'Sabeela',    'James',  'Willams',    'Malik',   'Amrish',
    'Vince',   'Suresh',   'Esther',    'Yusuf',    'Komal',    'Veena',
    'Shree',   'Roshan',   'Sudeep',    'Vinne',    'Vidya',   'Arvind',
    'Kumar',      'Amy',     'Ravi',   'Sheeba',      'Ram',  'Rumaiza',
    'Aditi',    'Surya']
Length: 50, dtype: str

In [10]:
df["Category"].unique()

<StringArray>
[     'Oil & Masala',         'Beverages',       'Food Grains',
  'Fruits & Veggies',            'Bakery',            'Snacks',
 'Eggs, Meat & Fish']
Length: 7, dtype: str

In [11]:
df["Sub Category"].unique()

<StringArray>
[           'Masalas',      'Health Drinks',       'Atta & Flour',
   'Fresh Vegetables',    'Organic Staples',       'Fresh Fruits',
           'Biscuits',              'Cakes',         'Chocolates',
               'Eggs',            'Cookies',            'Chicken',
  'Edible Oil & Ghee',             'Mutton',        'Soft Drinks',
      'Dals & Pulses', 'Organic Vegetables',            'Noodles',
     'Organic Fruits',               'Fish',             'Spices',
               'Rice',      'Breads & Buns']
Length: 23, dtype: str

In [12]:
df["City"].unique()

<StringArray>
[       'Vellore',    'Krishnagiri',     'Perambalur',     'Dharmapuri',
           'Ooty',         'Trichy', 'Ramanadhapuram',    'Tirunelveli',
        'Chennai',          'Karur',       'Namakkal',       'Dindigul',
    'Kanyakumari',           'Bodi',        'Tenkasi',     'Viluppuram',
        'Madurai',          'Salem',         'Cumbum',      'Nagercoil',
     'Pudukottai',          'Theni',     'Coimbatore',   'Virudhunagar']
Length: 24, dtype: str

In [13]:
df["Region"].unique()

<StringArray>
['North', 'South', 'West', 'Central', 'East']
Length: 5, dtype: str

In [14]:
df["Order Date"].sample(5)

8833    10-06-2017
4868    12/15/2016
8587    11-09-2015
7349     8/24/2018
9759    11-12-2018
Name: Order Date, dtype: str

In [15]:
#After viewing the irreugular date. 
#This line converts the "Order Date" column in your pandas DataFrame from strings into actual datetime objects.
df["Order Date"] = pd.to_datetime(df["Order Date"], format="mixed")
df["Order Date"].sample(5)

2334   2018-06-10
5197   2018-11-23
5548   2018-09-19
5478   2018-11-17
6177   2015-03-22
Name: Order Date, dtype: datetime64[us]

In [16]:
#Extracting year, month, date from the order date column
df['Year'] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month_name()
df["Date"] = df["Order Date"]. dt.day

In [20]:
'''i am extracting discount amount from the discount percentage by using the simple formula: CP = (SP*100/ 100-Discount percent)
and then we are subtracting CP from SP to get discount amount '''

df["Discount_Amt"] = round((df["Sales"]*100)/(100-(df["Discount"]*100))).astype(int) - df["Sales"]

In [21]:
#removing the order date column
df.drop(["Order Date", "Discount"], axis=1, inplace=True)

In [23]:
#final dataframe
df.head(6)

,Customer Name,Category,Sub Category,City,Region,Sales,Profit,State,Year,Month,Date,Discount_Amt
0,Harish,Oil & Masala,Masalas,Vellore,North,1254,401.28,Tamil Nadu,2017,November,8,171
1,Sudha,Beverages,Health Drinks,Krishnagiri,South,749,149.80,Tamil Nadu,2017,November,8,164
2,Hussain,Food Grains,Atta & Flour,Perambalur,West,2360,165.20,Tamil Nadu,2017,June,12,627
3,Jackson,Fruits & Veggies,Fresh Vegetables,Dharmapuri,South,896,89.60,Tamil Nadu,2016,October,11,299
4,Ridhesh,Food Grains,Organic Staples,Ooty,South,2355,918.45,Tamil Nadu,2016,October,11,827
5,Adavan,Food Grains,Organic Staples,Dharmapuri,West,2305,322.70,Tamil Nadu,2015,June,9,810

In [24]:
#count of product sold in each Category
df["Category"].value_counts()

Category
Snacks               1514
Eggs, Meat & Fish    1490
Fruits & Veggies     1418
Bakery               1413
Beverages            1400
Food Grains          1398
Oil & Masala         1361
Name: count, dtype: int64

In [25]:
# Count of products sold in each Sub Category
df["Sub Category"].value_counts()

Sub Category
Health Drinks         719
Soft Drinks           681
Cookies               520
Breads & Buns         502
Chocolates            499
Noodles               495
Masalas               463
Biscuits              459
Cakes                 452
Edible Oil & Ghee     451
Spices                447
Mutton                394
Eggs                  379
Organic Staples       372
Fresh Fruits          369
Fish                  369
Fresh Vegetables      354
Atta & Flour          353
Chicken               348
Organic Fruits        348
Organic Vegetables    347
Dals & Pulses         343
Rice                  330
Name: count, dtype: int64

In [26]:
# Count of products sold in each City
df["City"].value_counts()

City
Kanyakumari       459
Tirunelveli       446
Bodi              442
Krishnagiri       440
Vellore           435
Perambalur        434
Chennai           432
Tenkasi           432
Salem             431
Karur             430
Pudukottai        430
Coimbatore        428
Ramanadhapuram    421
Cumbum            417
Virudhunagar      416
Madurai           408
Ooty              404
Namakkal          403
Viluppuram        397
Dindigul          396
Theni             387
Dharmapuri        376
Nagercoil         373
Trichy            357
Name: count, dtype: int64

In [27]:
df["Region"].value_counts()

Region
West       3203
East       2848
Central    2323
South      1619
North         1
Name: count, dtype: int64